### ISSUE TITLE
?

### ISSUE THREAD

**Issue by k33g** [PolytechLyon/tp-mvc-grp2-isi3_jolivet_mounier_tp6#1]
@mounieju avez vous terminé?

**Comment by mounieju** [comment]
Ce n'est ni un problème de nommage de route ni de méthode, nous ne savons pas pourquoi lorsqu'on clique sur le bouton, la fonction n'est pas appelée (nous avons mis un point d'arret sur la méthode delete de FoodController, et il n'est pas atteint lorsqu'on clique sur le bouton supprimer)
