### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by natos33** [PolytechLyon/tp-mvc-grp2-isi3_jolivet_mounier_tp6#2]
Bonjour, 
Nous aimerions que vous regardiez le code et le rapport pour nous dire ce que vous en pensez.
Nous n'avons pas réussi à arranger notre problème de suppression des ingrédients pour le second exercice et nous ne comprenons pas pourquoi la suppression ne fonctionne pas, peut être pouvez vous nous expliquer notre erreur si vous la trouvez.

Merci d'avance

**Comment by k33g** [comment]
vous auriez pu faire un lien au lieu d'un bouton pour voir si cela fonctionne mieux
`<a class="button" href="/deleteFood?id={{@index}}"`
